definitions:
  model_common.ResponseError:
    properties:
      date:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  model_common.StandardErrorModel:
    properties:
      error:
        $ref: '#/definitions/model_common.ResponseError'
    type: object
  model_minio.MinioURL:
    properties:
      url:
        type: string
    type: object
  model_user_service.ForgetPasswordVerify:
    properties:
      cade:
        example: 7777
        type: integer
      new_password:
        example: new_password
        type: string
      phone_number:
        example: "+998950230605"
        type: string
    type: object
  model_user_service.LoginReq:
    properties:
      fcm_token:
        type: string
      password:
        example: password
        type: string
      phone_number:
        example: "+998950230605"
        type: string
      platform_name:
        type: string
      platform_type:
        example: mobile
        type: string
    type: object
  model_user_service.MessageRes:
    properties:
      message:
        type: string
    type: object
  model_user_service.PhoneNumberReq:
    properties:
      phone_number:
        example: "+998950230605"
        type: string
    type: object
  model_user_service.RegisterRequest:
    properties:
      birth_date:
        example: "2000-01-01"
        type: string
      first_name:
        example: Ali
        type: string
      gender:
        example: male
        type: string
      last_name:
        example: Jo'raxonov'
        type: string
      password:
        example: password
        type: string
      phone_number:
        example: "+998950230605"
        type: string
    type: object
  model_user_service.Response:
    properties:
      access_token:
        type: string
      birth_date:
        type: string
      first_name:
        type: string
      gender:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
    type: object
  model_user_service.Verify:
    properties:
      code:
        example: 7777
        type: integer
      fcm_token:
        type: string
      phone_number:
        example: "+998950230605"
        type: string
      platform_name:
        type: string
      platform_type:
        example: mobile
        type: string
    type: object
host: localhost:9050
info:
  contact: {}
  title: API
  version: "1.7"
paths:
  /v1/customer/forget_password:
    post:
      consumes:
      - application/json
      description: ForgetPassword - Api for registering users
      parameters:
      - description: RegisterModelReq
        in: body
        name: ForgetPassword
        required: true
        schema:
          $ref: '#/definitions/model_user_service.PhoneNumberReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model_user_service.MessageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
      summary: ForgetPassword
      tags:
      - customer
  /v1/customer/forget_password_verify:
    post:
      consumes:
      - application/json
      description: ForgetPasswordVerify - Api for registering users
      parameters:
      - description: RegisterModelReq
        in: body
        name: Verify
        required: true
        schema:
          $ref: '#/definitions/model_user_service.ForgetPasswordVerify'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model_user_service.MessageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
      summary: ForgetPasswordVerify
      tags:
      - customer
  /v1/customer/login:
    post:
      consumes:
      - application/json
      description: Login - Api for registering users
      parameters:
      - description: Login Req
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/model_user_service.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model_user_service.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
      summary: Login
      tags:
      - customer
  /v1/customer/logout:
    get:
      consumes:
      - application/json
      description: LogOut - Api for registering users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model_user_service.MessageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
      security:
      - ApiKeyAuth: []
      summary: LogOut
      tags:
      - customer
  /v1/customer/register:
    post:
      consumes:
      - application/json
      description: Register - Api for registering users
      parameters:
      - description: RegisterRequest
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/model_user_service.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model_user_service.MessageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
      summary: Register
      tags:
      - customer
  /v1/customer/verify:
    post:
      consumes:
      - application/json
      description: customer - Api for registering users
      parameters:
      - description: RegisterModelReq
        in: body
        name: Verify
        required: true
        schema:
          $ref: '#/definitions/model_user_service.Verify'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model_user_service.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
      summary: Verify
      tags:
      - customer
  /v1/file-upload:
    post:
      consumes:
      - image/png
      description: Upload image
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model_minio.MinioURL'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model_common.StandardErrorModel'
      summary: Upload image
      tags:
      - upload-file
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
